### ISSUE TITLE
CoinMarketCap Token 

### ISSUE THREAD

**Issue by captainsubtext** [abhinavk99/crypto-bot#3]
When i type /info btc i get the error:

(node:12888) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'find' of undefined
    at C:\Users\julia\Desktop\crypto-bot-master\bot.js:46:39
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:12888) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise 
which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)

I'm not 100% sure but i miss the coinmarketcap_token.

**Comment by abhinavk99** [comment]
Thanks for bringing up this issue! To tell you the truth, I haven't worked on this bot for ages, so it's outdated. I ran the bot locally and got the same error as you so I'm going to check if fixing is possible.

**Comment by abhinavk99** [comment]
It turns out that I made this bot before CoinMarketCap changed their API and made a token mandatory, so I'm going to have to update the bot to take into account the changes.

**Comment by abhinavk99** [comment]
@captainsubtext I fixed the code and released v3 so it should be working now. Please clone the repo again and read the updated README.md. You now need to add `COINMARKETCAP_KEY=key` to your .env file.
